remote_theme: tedivm/jekyll-theme-portfolio

title: Phost's Projects
author: Phost
email: me@phost.dev
description: >
  Projects by phost

# Header Links - all optional. If set these create header links.
homepage: https://phost.dev
#twitter_username: example
github_username: 2phost
#linkedin_username: example

plugins:
 - jekyll-feed
 - jekyll-seo-tag
 - jekyll-remote-theme # Lets us test remote themes locally.

# TESTE
header_pages:
 - blog.md
